#!/usr/bin/env bash
# Displays DNS information for specified domain and subdomains

get_dns_info() {
    local domain=$1
    local subdomain=$2
    local full_domain
    
    if [ -z "$subdomain" ]; then
        full_domain="${subdomain}.${domain}"
    else
        full_domain="${subdomain}.${domain}"
    fi
    
    # Query DNS and extract relevant information
    dig "$full_domain" | awk -v sd="$subdomain" '
        /^;; ANSWER SECTION:/ {getline; print "The subdomain " sd " is a " $4 " record and points to " $5}
    '
}

main() {
    local domain=$1
    local subdomain=$2
    
    if [ -z "$subdomain" ]; then
        # Check default subdomains in order
        get_dns_info "$domain" "www"
        get_dns_info "$domain" "lb-01"
        get_dns_info "$domain" "web-01"
        get_dns_info "$domain" "web-02"
    else
        get_dns_info "$domain" "$subdomain"
    fi
}

main "$@"