#!/bin/bash
# Configure Nginx redirection

# Install Nginx if not already installed
apt-get update -y
apt-get install nginx -y

# Create redirection configuration
cat > /etc/nginx/sites-available/default <<EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOL

# Restart Nginx
service nginx restart