#!/usr/bin/env bash
# Configures Nginx with custom header X-Served-By

# Install Nginx if not already installed
apt-get update -y
apt-get install nginx -y

# Get server hostname
HOSTNAME=$(hostname)

# Configure Nginx with custom header
cat > /etc/nginx/conf.d/custom_header.conf <<EOF
add_header X-Served-By $HOSTNAME;
EOF

# Create default page if it doesn't exist
if [ ! -f /var/www/html/index.nginx-debian.html ]; then
    echo "Hello World!" > /var/www/html/index.nginx-debian.html
fi

# Restart Nginx
service nginx restart